### ISSUE TITLE
Element 'Principal' does not match any field or property of class Microsoft.AspNetCore.Identity.UserLoginInfo.

### ISSUE THREAD

**Issue by Yandawl** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#1]
Hi there,

I'm getting this exception on several methods when I'm trying to check a user exists (FindByEmail, FindByUsername) before creating a new one and on creating a new user. I don't think I can find a way around this.

From what I can tell, this is coming from trying to serialise the Logins property of MongoIdentityUser, of which the Principal property is empty, after adding a login to the user.

This is happening after the user is initially created. I'm able to create a user, add logins, and sign in to my application on the first attempt.

Any help would be appreciated!

**Comment by alexandre-spieser** [comment]
Hello,

This is what the UserLoginInfo looks like in Microsoft.Extensions.Identity.Core, Version=2.0.1.0.

```
#region Assembly Microsoft.Extensions.Identity.Core, Version=2.0.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
// C:\Program Files\dotnet\sdk\NuGetFallbackFolder\microsoft.extensions.identity.core\2.0.1\lib\netstandard2.0\Microsoft.Extensions.Identity.Core.dll
#endregion

namespace Microsoft.AspNetCore.Identity
{
    //
    // Résumé :
    //     Represents login information and source for a user record.
    public class UserLoginInfo
    {
        //
        // Résumé :
        //     Creates a new instance of Microsoft.AspNetCore.Identity.UserLoginInfo
        //
        // Paramètres :
        //   loginProvider:
        //     The provider associated with this login information.
        //
        //   providerKey:
        //     The unique identifier for this user provided by the login provider.
        //
        //   displayName:
        //     The display name for this user provided by the login provider.
        public UserLoginInfo(string loginProvider, string providerKey, string displayName);

        //
        // Résumé :
        //     Gets or sets the provider for this instance of Microsoft.AspNetCore.Identity.UserLoginInfo.
        //
        // Notes :
        //     Examples of the provider may be Local, Facebook, Google, etc.
        public string LoginProvider { get; set; }
        //
        // Résumé :
        //     Gets or sets the unique identifier for the user identity user provided by the
        //     login provider.
        //
        // Notes :
        //     This would be unique per provider, examples may be @microsoft as a Twitter provider
        //     key.
        public string ProviderKey { get; set; }
        //
        // Résumé :
        //     Gets or sets the display name for the provider.
        public string ProviderDisplayName { get; set; }
    }
}
```

There is no property or field called Principal. Are you sure you are using the `UserLoginInfo ` from the `Microsoft.Extensions.Identity.Core` namespace?

**Comment by Yandawl** [comment]
Hiya, yeah. The extra fields get added to the Logins collection when I call AddLoginAsync(ApplicationUser, EternalLoginInfo)

**Comment by Yandawl** [comment]
Here is the exception:

[](http://prntscr.com/hzncbw)

**Comment by alexandre-spieser** [comment]
I see.
There is no implementation using ExternalLoginInfo, only UserLoginInfo is supported for the moment.
Even MS tests do not use ExternalLoginInfo. For example [here].(https://github.com/aspnet/Identity/blob/85f8a49aef68bf9763cd9854ce1dd4a26a7c5d3c/test/InMemory.Test/ControllerTest.cs).

On line 104 : 
`IdentityResultAssert.IsSuccess(await userManager.AddLoginAsync(user, new UserLoginInfo(authScheme, externalId, "whatever")));`
The reason why it was building was because ExternalLoginInfo inherits from UserLoginInfo .
You must down cast it to UserLoginInfo, or make your own implementation handling the type: ExternalLoginInfo.

I will make sure that the added info does not have extra properties in the future.

In the mean time, if you want to keep the claims from the principal you can add them to the MongoClaims.

**Comment by Yandawl** [comment]
Ahhhhh! I didn't spot that at all. Thank you for the help. Great piece of work btw!

**Comment by alexandre-spieser** [comment]
https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/commit/17b38aeb3f84a880de0a09b2731a6cef8652ebbc
Committed a fix to prevent that in the future.
