### ISSUE TITLE
Issue when using UserStore in my Service Layer.

### ISSUE THREAD

**Issue by kunalpgithub** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#10]
Thank you for this awesome library, to integrate .net identity with Mongo DB.

Have worked well so far, except for this issue I am facing with using userStore instead of userManager.

So I need to fetch user by  its Id, since its needed in service layer, I am trying to userStore and not manager.

But when I try to inject UserStore<User>...it complains that it can not convert from User<ObjectId> to User<string>.

I have seen UserStore class and it loosk like its implemented only for string type , not able to figure out why its complaining. I thought it should be generic instead of just string.

**Comment by alexandre-spieser** [comment]
Hi,
Thanks.

Have you made sure that your User type is in the right namespace and that it inherits the type `MongoIdentityUser<T>`?

```
public class ApplicationUser : MongoIdentityUser<Guid>
{
	public ApplicationUser() : base()
	{
	}

	public ApplicationUser(string userName, string email) : base(userName, email)
	{
	}
}
```
