### ISSUE TITLE
Can I expire the session using your example?

### ISSUE THREAD

**Issue by CarlosTorrecillas** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#12]
Hi @alexandre-spieser ,

I took this package and was running through your example as well as the standard IdentityServer4 Quickstart one https://github.com/IdentityServer/IdentityServer4.Quickstart.UI and my question is regarding logging out / expiring tokens. Is it possible to perform that via the sign in manager you use in your example? At the moment I wasn't able to perform a log in establishing how long the token would be valid or whether I want to be remembered for, let's say one day. Also, and I'm not sure if that could be related, when I clone tabs and perform a log out, the other tab keeps being logged in and the token/session seems to be still active.

I have posted a more detailed question in StackOverflow: https://stackoverflow.com/questions/55168608/sign-out-from-all-sessions-identityserver4 but I would appreciate if you could tell me whether you came across that issue before or know of any example I could have a look at.

Thanks!

**Comment by alexandre-spieser** [comment]
Hi, this package uses AspNet.Identity that does not have the laster changes regarding IdentityServer.
To Signout you should be able to use the SigninManager.Signout() method.

You can look at the usage of the package in here:
https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/tree/master/sample/MongoIdentitySample.Mvc/Controllers

**Comment by CarlosTorrecillas** [comment]
Thanks for getting back to me. Have to tried to open multiple tabs in your browser and sign out from one of them? Do the other tabs log off as well? I say that because that's the issue I'm facing right now.
My log out looks like this:
```
/// <summary>
/// Show logout page
/// </summary>
[HttpGet]
public async Task<IActionResult> Logout(string logoutId)
{
      var logoutContext = await _interaction.GetLogoutContextAsync(logoutId);

      await _signInManager.SignOutAsync();

      return Redirect(logoutContext.PostLogoutRedirectUri);
}

```

**Comment by alexandre-spieser** [comment]
The action in the MVC sample is a Post. Not sure about what the _interaction dependency does.

**Comment by xclud** [comment]
@CarlosTorrecillas You cannot have different sessions in different browser tabs/instances. Authentication works based on Cookies and they provide the same info browser-wide.

This mean if you log-in all browser tabs are logged in and the same if you log out. So `logoutId` won't help.

One solution might be JWT based authentication and not even storing the token in cookies or localStorage. You can save the token in `window.token` for instance.

**Comment by CarlosTorrecillas** [comment]
Ok - I understand that. What I would have imagined then is that, if I log out in one of the tabs, then the other one would also be “logged-out” if that makes sense, but it’s not the case. For some reason the user is still able to run authenticated actions. Does that make sense?

**Comment by xclud** [comment]
As long as i know oidc-client works in two modes: localStorage and sessionStorage. It depends on your configuration. If you are on localStorage then logging out in a tab logs out everywhere else. But if you are on sessionStorage mode, only one tab logs out (you don't even need to log out, closing browser tab is enough).

More on localStorage and sessionStorage:
https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage

oidc-client's behavior is set to sessionStorage by default:
https://github.com/IdentityModel/oidc-client-js/blob/8848a6c58bbc41342e11888df2eb44ad117da94a/src/UserManagerSettings.js#L35

**Comment by alexandre-spieser** [comment]
If it's token based authentication stored in a cookie, you're better off writing middleware that expires your session simply by taking the specific cookie and making it expire.

**Comment by xclud** [comment]
In addition to my previous comment, in sessionStorage you will need to log-in for each tab separately.

**Comment by alexandre-spieser** [comment]
If you're set on using IdentityServer and it's not supported by MS Identity then you must handle the token management yourself.
I am using OpenIdConnectServer as a token provider in my personal projects, and I just use AspNetCore.Identity.MongoDbCore  to do the user management, not the session management.

**Comment by xclud** [comment]
Right, you may not mix a client-side library with server-side auth. 

I believe the best solution is to use oidc-client with a web-api project with a token based auth.

Alternately, you can get rid of oidc-client and use Startup.Configure function to disable cookie auth and use a sesstionStorage thing. It might need to write a middleware.

**Comment by CarlosTorrecillas** [comment]
Hi @alexandre-spieser @xclud , I managed to expire all active sessions on different tabs eventually. When you sign out there is an event fired and the OIDC client picks it up. You can then add a handler to it to sign out automatically and that would do it:

```
this.manager.events.addUserSignedOut(() => {
            this.signOut();
        });
```
Simply like that! I have faced anti forgery token issues later on when trying to log in multiple times from different tabs but I think I got that resolved too.

Many thanks for the help!!!

**Comment by alexandre-spieser** [comment]
Glad you could make it work.
I'm a closing this issue 👍
