### ISSUE TITLE
Not able to update user.

### ISSUE THREAD

**Issue by kunalpgithub** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#15]
Can you share an example of how to update User.

I am using this method to update user.

var result = await UserManager.UpdateAsync(AppUser).ConfigureAwait(false);

Do I need to implment customUserStore or can use existing mongoUserStore to update user?

**Comment by alexandre-spieser** [comment]
the existing mongodb userstore should work.
Please look at the MVC sample for usages ;)

**Comment by kunalpgithub** [comment]
@alexandre-spieser there is no usage of mongodb userstore.

Also when I try to use MongodbUserStore , it only accepts MongoDbUserStore of type User with key as string type, while I have user with key as objectId.

In sample or documentation I don't find custom implementation of MongoDbUserStore.

**Comment by alexandre-spieser** [comment]
Do you register the stores for DI? 
Based on the docs your documents must inherit from `MongoIdentityUser<ObjectId>`.
The registration in your Startup.cs file should have:
```
var mongoDbContext = new MongoDbContext("mongodb://localhost:27017", "MongoDbTests");
services.AddIdentity<ApplicationUser, ApplicationRole>()
	.AddMongoDbStores<ApplicationUser, ApplicationRole, ObjectId>(mongoDbContext)
	.AddDefaultTokenProviders()
```

**Comment by kunalpgithub** [comment]
Yes I did that but it doesn't work.

Tried this other method, that also didn't work.

 var mongoDbIdentityConfiguration = new MongoDbIdentityConfiguration {
                MongoDbSettings = settings,
                IdentityOptionsAction = options =>
                {
                    options.SignIn.RequireConfirmedEmail = false;
                    // Password settings.
                    options.Password.RequireDigit = true;
                    options.Password.RequireLowercase = true;
                    options.Password.RequireNonAlphanumeric = true;
                    options.Password.RequireUppercase = true;
                    options.Password.RequiredLength = 6;
                    options.Password.RequiredUniqueChars = 1;

                    // Lockout settings.
                    options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(5);
                    options.Lockout.MaxFailedAccessAttempts = 5;
                    options.Lockout.AllowedForNewUsers = true;

                    // User settings.
                    options.User.AllowedUserNameCharacters =
                    "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789-._@+";
                    options.User.RequireUniqueEmail = true;
                }
            };
            services.ConfigureMongoDbIdentity<User, UserRole, ObjectId>(mongoDbIdentityConfiguration);

**Comment by abstracthuman** [comment]
I'm fairly new to working with Azure Cosmos DB, but after setting up the base connection and ApplicationUser I'm only seeing the collection I've made explicit show up in the portal. Is there something I'm missing on the portal side or should AddMongoDbStores add the user collection and document record?

**Comment by alexandre-spieser** [comment]
Hi, it should create your user automatically.
For Azure Cosmos DB you need to set the Legacy UUID as default in the MongoDbContext that is used in the store.
Please refer to this issue with Cosmos DB:
https://github.com/alexandre-spieser/mongodb-generic-repository/issues/7

**Comment by alexandre-spieser** [comment]
Try that, basic example from the docs, I just added:
```
// create a MongoDbContext instance, default GuidRepresentation is set in constructor
var mongoDbContext = new MongoDbContext("mongodb://localhost:27017", "MongoDbTests");
// set the GuidRepresentation to Legacy for Cosmos db 
mongoDbContext.SetGuidRepresentation(MongoDB.Bson.GuidRepresentation.CSharpLegacy);
// pass the mongoDbContext to the store.
services.AddIdentity<ApplicationUser, ApplicationRole>()
	.AddMongoDbStores<IMongoDbContext>(mongoDbContext)
	.AddDefaultTokenProviders();
```
Note: I have not tested this, but from the people who reported the Cosmos issue, it works.
Happy easter!

**Comment by abstracthuman** [comment]
@alexandre-spieser This makes sense and works perfectly! I additionally just needed to make sure the connection string also had - &uuidRepresentation=CSharpLegacy for it to properly show up in Azure Cosmos DB. Happy Easter!

**Comment by alexandre-spieser** [comment]
Could still not reproduce original issue, I wrote more tests in this commit, it works as expected:
https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/commit/51a40cfd5702c6adc5180ce33f875d75b4829d31
