### ISSUE TITLE
how can I user this in asp.net core 3.0 ?

### ISSUE THREAD

**Issue by iwaitu** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#16]
asp.net core 3.0 default code like this：

`services.AddIdentityServer()
            .AddApiAuthorization<ApplicationUser, ApplicationDbContext>();`

it use identityserver to provider jwt Authorization, Can you update this package ?

**Comment by alexandre-spieser** [comment]
How can I use this in asp.net core 3.0 <= not really possible for now, they wrote a lot of classes using IdentityServer's open source project code, Identity 3.0 != Identity 2.0. 
IdentityServer's data access layer is different than Identity 2.0, it has additional docs to store. It's a massive update.
I'll look at their docs but can't promise anything, I'm pretty busy at the moment and doing other things in my free time.
