### ISSUE TITLE
UserManager filtering users not fully working

### ISSUE THREAD

**Issue by CarlosTorrecillas** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#17]
Hi @alexandre-spieser ,

Have you come across this issue before? I have a standard configuration of the MongoDbCore package which I have been using for a while. All works fine and today I wanted to filter the list of users based on a role. Looking around I found you can directly use the manager and apply some LINQ expressions like this:

```
applicationUsers = _userManager.Users
                                                      .Where(u => u.Roles.All(r => r != adminRole.Id))
                                                      .Skip((userSearch.Page - 1) * userSearch.PageSize)
                                                      .Take(userSearch.PageSize)
                                                      .ToList();
```

The thing is though, I got the following error: 

`System.ArgumentException: 'Unsupported filter: All({document}{Roles}.Where(({document} != 5724fdf9-83e3-4331-9f15-c9de9b243c09))).'`

So I'm not sure whether there is something I'm missing in terms of configuration or setup, but to get this working, I have to transform the `Users `property `ToList `and then apply the `LINQ `filter. I'm assuming that's not entirely right?

For reference I'm using v1.1.1 of the package

**Comment by alexandre-spieser** [comment]
Hi, thanks for reporting the issue, however it's a limitation for the MongoDB driver when doing LINQ to MongoDB query language. Not much I can do here, apart from upgrading the MongoDB.Driver if you know that it's supported kn newer versions.

Le 18 oct. 2019 09:26, Carlos Torrecillas <notifications@github.com> a écrit :

Hi @alexandre-spieser<https://github.com/alexandre-spieser> ,

Have you come across this issue before? I have a standard configuration of the MongoDbCore package which I have been using for a while. All works fine and today I wanted to filter the list of users based on a role. Looking around I found you can directly use the manager and apply some LINQ expressions like this:

applicationUsers = _userManager.Users
                                                      .Where(u => u.Roles.All(r => r != adminRole.Id))
                                                      .Skip((userSearch.Page - 1) * userSearch.PageSize)
                                                      .Take(userSearch.PageSize)
                                                      .ToList();


The thing is though, I got the following error:

System.ArgumentException: 'Unsupported filter: All({document}{Roles}.Where(({document} != 5724fdf9-83e3-4331-9f15-c9de9b243c09))).'

So I'm not sure whether there is something I'm missing in terms of configuration or setup, but to get this working, I have to transform the Users property ToList and then apply the LINQ filter. I'm assuming that's not entirely right?
