### ISSUE TITLE
Rename/Remove properties

### ISSUE THREAD

**Issue by RapaErik** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#19]
Hi !
I didn`t want to store some of from those properties like PhoneNumber and I want also to rename properties in mongo to lowercase. 
Is there  a method to do that?

I tried to override them and use annotation BsonIgnore or BsonElement but not works maybe it was a dumb idea.

Then I tried to create class mapper conform : https://mongodb-documentation.readthedocs.io/en/latest/ecosystem/tutorial/serialize-documents-with-the-csharp-driver.html
but I got NullRefferenceExeption maybe I done something wrong.

Could you help me please?

**Comment by alexandre-spieser** [comment]
This is a package for AspNet.Identity, so the user class must inherit from the IdentityUser<T> class.
Which is defined here : https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.identity.entityframeworkcore.identityuser-1?view=aspnetcore-1.1

If you want something custom you must have a custom class mapping configuration, please refer to the docs here:

https://mongodb.github.io/mongo-csharp-driver/2.3/reference/bson/mapping/

Note: this has nothing to do with this package, there a MongoDB Driver specific settings.
