### ISSUE TITLE
how to use this repositery in WEB api project, or can we use JWT token ?

### ISSUE THREAD

**Issue by davegautam** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#2]

**Comment by alexandre-spieser** [comment]
You can use the UserManager the same way as the SQL server one.

An sample MVC application is available in the repo:
https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/tree/master/sample/MongoIdentitySample.Mvc

This is just a data store adapter for using the Identity 2.0 on MongoDB. So you can use pretty much any form of authentication: cookies, tokens, anything really. You'll have to download the necessary packages for this.

**Comment by davegautam** [comment]
thank you ! will try the same
