### ISSUE TITLE
Running the sample in VS

### ISSUE THREAD

**Issue by MisinformedDNA** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#27]
I spent some hours trying to figure out how to run the sample in VS 2019 16.4.5 and then 16.5.4 (latest). I had SSL issues ("This site can’t provide a secure connection") followed by IIS issues ("Unable to connect to web server 'IIS Express').

Finally, I saw that a VSCode folder was checked in. So I ran the sample in VSCode and everything just worked. I never got it running in VS.

Is anyone else having issues running this in VS?

**Comment by MisinformedDNA** [comment]
I got it running. I think the only difference was that I had removed these two lines:

```
    <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
    <AspNetCoreModuleName>AspNetCoreModule</AspNetCoreModuleName>
```

But I haven't had a chance to validate that.

**Comment by Vertigo093i** [comment]
`InProcess` (default mode which you've set by removing those two lines) works just fine with 16.5.4 and 3.1.

Sometimes (saw this in earlier versions) you may get a misconfiguration between project and `applicationhost.config` file stored inside `.vs` folder. They might point to different process models. Check the latter or remove it entirely to allow VS to recreate it.
