### ISSUE TITLE
[Bug]: The name parameter is not set to the Name property in MongoIdentityRole class

### ISSUE THREAD

**Issue by mjebrahimi** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#29]
The name parameter is not set to the Name property in [MongoIdentityRole](https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/blob/57827c64b251fc727c68132a51a7c2ae34d16327/src/Models/MongoIdentityRole.cs#L97) class

```c#
public MongoIdentityRole(string name, TKey key)
{
	InitializeFields();
	Id = key;
	Name = Name;
}
```

**Comment by alexandre-spieser** [comment]
Good spot, merged and fixed.

**Comment by alexandre-spieser** [comment]
Releases

https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/releases/tag/2.1.1
