### ISSUE TITLE
Sign the assembly

### ISSUE THREAD

**Issue by AssafTzurEl** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#32]
When building code using AspNetCore.Identity.MongoDbCore, I get the following warning:
```
CS8002	Referenced assembly 'AspNetCore.Identity.MongoDbCore, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have a strong name.
```

Please sign it. TIA!

**Comment by alexandre-spieser** [comment]
I do not think I'm ready to pay $200+/year for a cert yet, just to sign 1 open source package.
Seems like they does not accept self signed so unless there is an alternative, it's not going to happen.

**Comment by AssafTzurEl** [comment]
I'm using self-certs in my solution for my own, local NuGets, and it seems to work fine. Who is "they" who do not accept it? GitHub?

**Comment by alexandre-spieser** [comment]
Nuget.org Looked into it further: you can possibly add me as a trusted owner (that is, if you trust me :D)Interesting thoughts found in the article below:https://haacked.com/archive/2019/04/03/nuget-package-signing/Le 16 juil. 2020 17:47, Assaf Tzur-El <notifications@github.com> a écrit :
I'm using self-certs in my solution for my own, local NuGets, and it seems to work fine. Who is "they" who do not accept it? GitHub?

**Comment by AssafTzurEl** [comment]
Thanks! Good article :)
