### ISSUE TITLE
Is it possible to use with older version of Asp.net Indentity versions below 2.0? 

### ISSUE THREAD

**Issue by jyothishwhatshalliget** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#36]
I can see that the Asp.net Indentity implementation in this wil have nomalizedemail and normalizedusername etc. I have an existing app and I want to use this package against the existing database. Is it possible to authenticate against the existing users in the database which was created with older version of aspnet identity?

**Comment by alexandre-spieser** [comment]
Hello, thanks for your interest in this package :) It depends, what is the type of the Id ? If it's Guid this package uses the non-legacy UUID format which my cause issues if you are using the MongoDB CShard driver with default settings (it's using legacy UUID subtype by default).Also you need to make sure that the document schema is the same as your existing data. Which older version of Identity are we talking about? Le 31 août 2020 07:02, jyothishwhatshalliget <notifications@github.com> a écrit :
I can see that the Asp.net Indentity implementation in this wil have nomalizedemail and normalizedusername etc. I have an existing app and I want to use this package against the existing database. Is it possible to authenticate against the existing users in the database which was created with older version of aspnet identity?

**Comment by jyothishwhatshalliget** [comment]
Hi, Im using ObjectId itself. I can provide a sample document object, which was a custom one, Added additional attributes to the identity user. Here is the existing version schema
`{"_id":{"$oid":"5b6ac5f720080f04fcd2c9c2"},"userName":"912222222222","securityStamp":"8aa833e7-4b6f-473f-9067-1590250abdd8","email":"test.testuser@gmail.com","emailConfirmed":false,"phoneNumber":"912222222222","phoneNumberConfirmed":false,"twoFactorEnabled":false,"lockoutEndDateUtc":null,"lockoutEnabled":false,"accessFailedCount":0,"roles":["App-User"],"passwordHash":"ANFylvfVA/jAdFbO0lSU4g4zFSyZKmovRnZrbYiCnb3At6AdebSwjZRi/k72Sn4J9A==","logins":[],"claims":[],"verificationCode":"9174","fullName":"Demo2 User2","photoPath":"http://ss.net/Images/Users/5b6ac5f720080f04fcd2c9c2/0aff7ad0-ab8a-434a-b2fe-1d03d9399af5.jpg","gender":77,"password":"","countryID":1,"languageID":1,"Status":"Available","statusText":"Hi There, I am a fan of WhatshalliGet","seeMyProfilePhoto":0,"seeMyPersonalInfo":0,"seeMyStatus":0,"SocialProvider":"facebook","ProviderKey":"23473735800","FeedbackSubmitted":false,"createdOn":{"$date":"0001-01-01T00:00:00.000Z"},"lastModifiedOn":{"$date":"2018-08-12T19:44:39.744Z"},"MemmorableDates":[],"devices":[{"deviceInfoID":{"$oid":"000000000000000000000000"},"deviceID":"d3W0_7z4jjI:APA91bGrp_NWltj1JWy2z-tcrhfedRbGrYOO5uflhY387PvHgzqPm4zinIKjWFkBRTYp-43fEmzm6J3iGZEFbe0u69pW4ffaia5Ciu6F4Xe3dmTX0MelwtIXjoA5u56-tpfuZJ1arSAa","oS":"Android"}],"myList":null,"myMembers":null}`

**Comment by alexandre-spieser** [comment]
I do not think it's possible, the schema looks quite different. You should probably migrate to a new collection with a different schema.
