### ISSUE TITLE
Using scoped storage

### ISSUE THREAD

**Issue by 0xorial** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#37]
I want to use multiple databases from a single app. This is resolved by using scopes instead of singletons for DI, but this library seems to use singletons. Is it possible to workaround that somehow?

**Comment by alexandre-spieser** [comment]
Hi, within the Identity domain, currently 1 DB can be used by default unless you setup some custom DI for each store?
Registraction happens in this class.
https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/blob/dd5619536663d32571a2c91ed698a74b0cd99788/src/Extensions/ServiceCollectionExtension.cs#L77
However for other data domains you can create another DB context and resolve under an interface other than IMongoDbContext.

**Comment by alexandre-spieser** [comment]
Yes you'd have to also pass the tenantid to some kind of service locator class to instanciate the identity classes with the correct connection creds.
