### ISSUE TITLE
Basic tutorial for Blazor and dotnet 5

### ISSUE THREAD

**Issue by przemo1983** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#38]
Could you please prepare vary basic tutorial for using this lib with Blazor and dotnet 5.0?
I mean basic login, registration and logout functionalities only.

**Comment by mayankjanmejay** [comment]
I second this !!

Please!

**Comment by alexandre-spieser** [comment]
I do not think this is part of the scope of this package, as this involves Identity Server configs, this package just replaces the SQL stores by MongoDB stores.
