### ISSUE TITLE
Unable to post Register using sample project.

### ISSUE THREAD

**Issue by mayankjanmejay** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#39]
Hi, 

I downloaded and configured your MVC sample project. I am able to register & login via the browser but when I try to replicate the Register request via postman. I keep getting 400, Bad request. 

Please help.

Is there something I am missing from the headers?

![image](https://user-images.githubusercontent.com/35850067/105992900-544f6f00-60ae-11eb-87dc-c70ea3808ec2.png)

![image](https://user-images.githubusercontent.com/35850067/105992700-1ce0c280-60ae-11eb-9537-8dbd881362b8.png)

https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/tree/master/sample/MongoIdentitySample.Mvc

**Comment by alexandre-spieser** [comment]
Hello, the field values look wrong: Email is value is not correct, password value is not correct either. Please debug to get the correct validation errors.Le 27 janv. 2021 12:46, Mayank Janmejay <notifications@github.com> a écrit :
Hi,
I downloaded and configured your MVC sample project. I am able to register & login via the browser but when I try to replicate the Register request via postman. I keep getting 400, Bad request.
Please help.
Is there something I am missing from the headers?


https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/tree/master/sample/MongoIdentitySample.Mvc

**Comment by mayankjanmejay** [comment]
Hi, 

As you suggested I corrected the fields and checked the process using breakpoints. When I use the accompanied UI the breakpoint gets activated and everything works but when still when I replicate everything via postman even the breakpoint does not get activated. 
![image](https://user-images.githubusercontent.com/35850067/106000289-5538ce80-60b7-11eb-8dc0-ff955507f81c.png)
![image](https://user-images.githubusercontent.com/35850067/106000547-98933d00-60b7-11eb-931f-9334ee29df7a.png)

**Comment by alexandre-spieser** [comment]
That's very strange, have you tried to post using the front end?
The model is https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/blob/dd5619536663d32571a2c91ed698a74b0cd99788/sample/MongoIdentitySample.Mvc/Models/AccountViewModels/RegisterViewModel.cs#L9

I have not changed anything with respect to the Identity example from MSFT.

The form post takes place here:

https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/blob/dd5619536663d32571a2c91ed698a74b0cd99788/sample/MongoIdentitySample.Mvc/Views/Account/Register.cshtml#L1

Never used postman for testing it sorry.

**Comment by alexandre-spieser** [comment]
Glad you managed to find the issue.
No not really, I would start with a Identity Server 4 example, then read the docs about ASP.NET integration and see if I can retrofit identity 2 with mongodb support into it. :)

**Comment by alexandre-spieser** [comment]
I also suggested a middleware-approach for handling JWTs, using OpenIdconnect server. Which you can take inspiration from here: https://stackoverflow.com/questions/37398276/how-can-i-validate-a-jwt-passed-via-cookies/39386631#39386631

Hope this helps!

**Comment by mayankjanmejay** [comment]
I got it working with your suggestion. Thank you very much
