### ISSUE TITLE
Suggestion: ObjectId

### ISSUE THREAD

**Issue by UtopleMan** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#4]
Hi there

How about using the MongoDB native type ObjectId as identifier on Users and Roles? In order to support that type, the following changes has to be done:

MongoIdentityRole.cs line 84
                case "ObjectId":
                    Id = (TKey)(object)ObjectId.GenerateNewId();
                    break;

MongoIdentityUser.cs line 391
                case "ObjectId":
                    Id = (TKey)(object)ObjectId.GenerateNewId();
                    break;

**Comment by alexandre-spieser** [comment]
Hello, 

Thank you for your message, yes I was actually thinking about implementing this soon 😃 .

Will have a look at that this week and write some tests to make sure all is good 👍.

Cheers

**Comment by alexandre-spieser** [comment]
Released:
`Install-Package AspNetCore.Identity.MongoDbCore -Version 1.0.8`
Commit: 
1ec9d1123e663fdc7f374d26fa1d38c0db057db1
