### ISSUE TITLE
Issues with the 3.1.0 version

### ISSUE THREAD

**Issue by Vertigo093i** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#41]
1. Please align `nuspec` and `csproj` dependencies verisons: downgrage `csproj`'s ones to at least 3.1.8 (or better 3.1.0 or 3.1.1). Otherwise my project doesn't complile at all. Then don't worry - it's my duty to maintain actual runtime versions.
2. Please remove `Microsoft.VisualStudio.Web.BrowserLink` dependency - it's irrelevant here.

**Comment by alexandre-spieser** [comment]
Hello, thanks for spotting the BrowserLink issue, it's been removed in https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/releases/tag/3.1.1.
I have removed the nuspec and made the package build from the csproj directly to avoid inconsistencies in the future.
However I have left the version to 3.1.12, what's the problem that you have with it?

**Comment by Vertigo093i** [comment]
Great job, thank you!

The problem was the `nuspec` itself claiming the package depended on 3.1.8 while actually it was 3.1.12. Now the problem should have been gone.

**Comment by alexandre-spieser** [comment]
Cool, seems like it's resolved then :)
