### ISSUE TITLE
Update Readme

### ISSUE THREAD

**Issue by CarlosTorrecillas** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#43]
Hello there,

Once again, thanks for teh great work and the awesome library!

After the latest release 3.1, could you update the readme in order to know whether we have an equivalent for `AddDefaultTokenProviders()`. Taking a look at the release notes is not very clear to me if we still have to call the method somehow.

Thanks!

**Comment by alexandre-spieser** [comment]
Hello! No worries.
I've updated the readme by appending `.AddDefaultTokenProviders()` to the examples where I thought necessary (commit can be seen here https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/commit/a9903b140f09d5dc36e873f7cdddd5d4c471bdf2), did I miss any?
I am not aware of the equivalent of `AddDefaultTokenProviders()`, as it seems like it's still referenced in the latest versions of the framework.

**Comment by CarlosTorrecillas** [comment]
You have to forgive me...somehow I started getting errors on that method once I upgraded to the latest version of the package. All Seems to be fine. Again, apologies!
