### ISSUE TITLE
Use of IMongoClient instead of MongoClient

### ISSUE THREAD

**Issue by scottcollins** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#44]
I have an application that uses a custom ```IMongoClient``` implementation to support Polly for retries.  Any thoughts on changing the ```AddMongoDbStores``` method to accept an ```IMongoClient``` instead of a ```MongoClient```?  This wouldn't be a breaking change since ```MongoClient``` already implements ```IMongoClient``` and would give the flexibility for other implementations and mock testing.

The other change I'd like to discuss (or maybe instead of the one above) is to provide an overload of ```AddMongoDbStores``` that accepts a ```Func<IMongoClient>``` parameter that will be called the first time it needs the ```IMongoClient```.  The reason for this is that I need to access an ```IServiceProvider``` to get the ```IMongoClient``` since it has injection dependencies and doing it against the ```IServiceCollection``` is too early in the process.

**Comment by alexandre-spieser** [comment]
Hello, thanks for reaching out, the AddMongoDbStores accepts an IMongoDbContext as far as I can see. Which you can Mock, or have a customer implementation of, the default behaviour is https://github.com/alexandre-spieser/mongodb-generic-repository/blob/master/MongoDbGenericRepository/MongoDbContext.cs

You could also pass a IMongoDatabase that exposes your custom client.
https://github.com/alexandre-spieser/mongodb-generic-repository/blob/fe02d871f344c1f63e8fe5fe05319ac58debe71d/MongoDbGenericRepository/MongoDbContext.cs#L29
```
        /// <summary>
        /// The constructor of the MongoDbContext, it needs an object implementing <see cref="IMongoDatabase"/>.
        /// </summary>
        /// <param name="mongoDatabase">An object implementing IMongoDatabase</param>
        public MongoDbContext(IMongoDatabase mongoDatabase)
        {
            // Avoid legacy UUID representation: use Binary 0x04 subtype.
            InitializeGuidRepresentation();
            Database = mongoDatabase;
            Client = Database.Client;
        }
```

Regarding the other change, it seems like you have something very specific in mind, so you should write a custom identity builder extension. The source of `AddMongoDbStores ` is here, https://github.com/alexandre-spieser/AspNetCore.Identity.MongoDbCore/blob/master/src/Extensions/MongoDbIdentityBuilderExtensions.cs .


I'll probably want to copy and tweak this one based on your needs :
```
        /// <summary>
        /// Adds a MongoDb implementation of identity information stores.
        /// </summary>
        /// <typeparam name="TUser">The type representing a user.</typeparam>
        /// <typeparam name="TRole">The type representing a role.</typeparam>
        /// <typeparam name="TKey">The type of the primary key of the identity document.</typeparam>
        /// <param name="builder">The <see cref="IdentityBuilder"/> instance this method extends.</param>
        /// <param name="mongoDbContext"></param>
        public static IdentityBuilder AddMongoDbStores<TUser, TRole, TKey>(this IdentityBuilder builder, IMongoDbContext mongoDbContext)
                    where TUser : MongoIdentityUser<TKey>, new()
                    where TRole : MongoIdentityRole<TKey>, new()
                    where TKey : IEquatable<TKey>
        {
            if (mongoDbContext == null)
            {
                throw new ArgumentNullException(nameof(mongoDbContext));
            }

            builder.Services.TryAddSingleton<IMongoDbContext>(mongoDbContext);
            builder.Services.TryAddSingleton<IMongoRepository>(new MongoRepository(mongoDbContext));
            builder.Services.TryAddScoped<IUserStore<TUser>>(provider =>
            {
                return new MongoUserStore<TUser, TRole, IMongoDbContext, TKey>(provider.GetService<IMongoDbContext>());
            });

            builder.Services.TryAddScoped<IRoleStore<TRole>>(provider =>
            {
                return new MongoRoleStore<TRole, IMongoDbContext, TKey>(provider.GetService<IMongoDbContext>());
            });
            return builder;
        }
```

Hope this helps!
