### ISSUE TITLE
IDictionary<string, string> Properties missing on MongoClaim

### ISSUE THREAD

**Issue by Nfactor26** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#54]
**Description**
**System.Security.Claims.Claim** contains a property named **Properties of type IDictionary<string,string>**. 
When trying to add a new System.Security.Claims.Claim to a Role , any KeyValuePair<string,string> that was added to Claim->Properties is discarded since no mapping property exists on MongoClaim.
`RoleManager<TRole>.AddClaimAsync(TRole, System.Security.Claims.Claim)`

```
 var claimToAdd = new Claim("Type", "Value");
 claimToAdd.Properties.Add("Key", "Value");
 await roleManager.AddClaimAsync(role, claimToAdd);
```
**Expected**
Properties dictionary should be persisted as well.

**Actual**
Properties dictionary is discarded.

**Comment by alexandre-spieser** [comment]
Yes this does not seem to be on MSFT's Identity specs either.
You'll have to customize this on your side.
