### ISSUE TITLE
MongoDB connection string with options

### ISSUE THREAD

**Issue by renatogbp** [alexandre-spieser/AspNetCore.Identity.MongoDbCore#9]
My mongodb connection string looks like: 
"mongodb://user:password@localhost:27017/Identity?ssl=true&authSource=admin"
when I break it to MongoDbSettings as 

`"MongoDbSettings": {
    "ConnectionString": "mongodb://user:password@localhost:27017/",
    "DatabaseName": "Identity?ssl=true&authSource=admin"
  }`

I can't connect to the database, am I doing something wrong?

**Comment by xclud** [comment]
Use '%23' instead of '#' in your password. Without quotes.

**Comment by xclud** [comment]
See the complete url encoding reference here:

https://www.w3schools.com/tags/ref_urlencode.asp

**Comment by alexandre-spieser** [comment]
Leave the connection string intact and just specify the DB Name in the second parameter:

 ```
           services.AddIdentity<TUser, TRole>()
                    .AddMongoDbStores<TUser, TRole, TKey>("mongodb://user:password@localhost:27017/Identity?ssl=true&authSource=admin", "Identity")
                    .AddDefaultTokenProviders();
```

**Comment by alexandre-spieser** [comment]
You can create a custom `MongoDbContext` with your desired parameters and pass it to the extension:

```
        public static IdentityBuilder AddMongoDbStores<TUser, TRole, TKey>(this IdentityBuilder builder, IMongoDbContext mongoDbContext)
                    where TUser : MongoIdentityUser<TKey>, new()
                    where TRole : MongoIdentityRole<TKey>, new()
                    where TKey : IEquatable<TKey>
```

To create a `MongoDbContext`, you can look in the `MongoDbGenericRepository` documentation, which is a dependency from the AspNetCore.Identity.MongoDbCore nuget package.

```
var client = new MongoClient(connectionString);
var mongoDbDatabase = Client.GetDatabase(databaseName);
```
There is a MongoDbContext constructor that takes a MongoDbDatabase.
```
        /// <summary>
        /// The constructor of the MongoDbContext, it needs a an object implementing <see cref="IMongoDatabase"/>.
        /// </summary>
        /// <param name="mongoDatabase">An object implementing IMongoDatabase</param>
        public MongoDbContext(IMongoDatabase mongoDatabase)
        {
            // Avoid legacy UUID representation: use Binary 0x04 subtype.
            InitializeGuidRepresentation();
            Database = mongoDatabase;
            Client = Database.Client;
        }
```
You can use a custom class inheriting from `MongoDbContext` that implements all the functionality you need, including a constructor or methods that takes a certificate.
The current implementation can be seen [here](https://github.com/alexandre-spieser/mongodb-generic-repository/blob/master/MongoDbGenericRepository/MongoDbContext.cs).
